# data engine and time range
data_source: tushare  # todo: add more options
data_condition:
  skip_download: True  # if already downloaded to local, skip it
  # benchmark to get market index,
  #  000001.XSHG: Shanghai securities composite index
  #  000300.XSHG: Shanghai and Shenzhen 300 index
  # for tushare, without payment, benchmark data not available
  benchmark: None # '000001.XSHG'
  # 交易所: SSE上交所 SZSE深交所 BSE北交所
  stock_pool: 'SSE'  # pool to select stock
  # todo: consider to read from csv
  stock_lst: []  # leave empty to acquire all
  stock_num: 10  # limit max train number for fast test, -1: use all
  time_freq: daily  # todo: add more options
  # todo: move date backward the length of ma_long
  train: [2018-01-01, 2019-12-30]
  eval: [2018-01-01, 2019-12-30]
  test: [2018-01-01, 2019-12-30]
  nan_process: drop  # drop, zero, mean, (todo) synthesis
  preprocess: [ 'normalization', 'standardization','de-extremum' ]
  # todo: for classification, u need to decide class number
  label_type: regression  # regression, classification

model_config:
  model_type: deep_forest
  kwargs:
    loss: RMSE
    learning_rate: 0.0421
    subsample: 0.8789
    max_depth: 6
    num_leaves: 100
    thread_count: 20
    grow_policy: Lossguide
    bootstrap_type: Poisson

backtest:
  account: 100000  # total money available for trading

  strategy_config:
    selection: mdl
    timing: mdl
    risk_ctrl: none
    portofolio: avg  # avg: average, weight: use weight
    # todo: trade price, close or mean
    trade_price: close

  order_cost:
    # Rf is risk-free interest rate, can be easily thought as
    #   Bank Deposit Rate, usually set as 0.04
    base_rate: 0.04
    close_tax: 0.001  # tax charged for selling
    open_commission: 0.0003  # purchase service fee
    close_commission: 0.0003  # selling service fee
    min_commission: 5  # minimum service fee for each trade
    slippage_fee: 0.0 #0.00246 # 0.00246  # fee difference between value and actual order
    # random: random pos or neg value, general: buy pos, sell neg
    slippage_type: general
    # calculate purchase number, 1 buy = 100 shares
    # minimum subscribe for 100 shares, multiple 100 is to 1 buy
    trade_lim: 100
